import SwiftUI

/// Represents all available sections and topics in the LinSolve app
/// Each section corresponds to a specific linear algebra concept or tool
enum AppSection: String, CaseIterable, Identifiable {
    case introduction = "Introduction"
    case matrixSetup = "Matrix Setup"
    case nullSpace = "Null Space"
    case columnSpace = "Column Space"
    case rowSpace = "Row Space"
    case leftNullSpace = "Left Null Space"
    case inverse = "Matrix Inverse"
    case determinant = "Determinant"
    case eigenvalues = "Eigenvalues"
    case eigenvectors = "Eigenvectors"
    case diagonalization = "Diagonalization"
    case gramSchmidt = "Gram-Schmidt & QR"
    case luDecomposition = "LU Decomposition"
    case svd = "Singular Value Decomposition"
    case orthogonality = "Inner Product & Orthogonality"
    case distanceHyperplane = "Distance to Hyperplane"
    case vectorArithmetic = "Vector Arithmetic"
    case linearCombinations = "Linear Combinations"
    case parallelVectors = "Parallel Vectors"
    case dotProductApplication = "Dot Product Application"
    case complexVectorArithmetic = "Complex Vector Arithmetic"
    case normalizationScaling = "Normalization & Scaling"
    case anglesBetweenVectors = "Angles Between Vectors"
    case orthogonalSets = "Orthogonal Sets"
    case matrixArithmetic = "Matrix Arithmetic"
    case matrixMultiplication = "Matrix Multiplication"
    case matrixExponents = "Matrix Powers"
    case transposeOperations = "Transpose Operations"
    case specialMatrixTypes = "Special Matrix Types"
    case verifySolutions = "Verify Solutions"
    case gaussianElimination = "Gaussian Elimination"
    case refRref = "REF & RREF"
    case gaussJordan = "Gauss-Jordan Method"
    case inverse2x2Formula = "2×2 Inverse Formula"
    case inverseGaussJordan = "Inverse via Gauss-Jordan"
    case solveWithInverse = "Solve with Inverse"
    case elementaryMatrices = "Elementary Matrices"
    case leastSquaresInconsistent = "Inconsistent System LS"
    case leastSquaresInfinite = "Infinite Solutions LS"
    case linearRegression = "Linear Regression"
    case quadraticCurveFitting = "Quadratic Curve Fitting"
    case geometric = "Geometric Visualization"
    case transformation2D = "2D Transformation"
    case rankNullity = "Rank-Nullity Theorem"
    case permutationsInversions = "Permutations & Inversions"
    case basicDeterminantCalc = "Basic Determinant Calculation"
    case geometricApplications = "Geometric Applications"
    case determinantProperties = "Determinant Properties"
    case cofactorExpansionMethod = "Cofactor Expansion Method"
    case adjugateInverse = "Adjugate & Inverse"
    case cramersRule = "Cramer's Rule"
    case orthogonalDiagonalization = "Orthogonal Diagonalization"
    case subspaceVerification = "Subspace Verification"
    case subspaceOperations = "Subspace Operations"
    case spanningSets = "Spanning Sets"
    case linearIndependenceBasic = "Basic Definition Testing"
    case linearIndependenceAlgorithms = "Systematic Algorithms"
    case findingBases = "Finding Bases"
    case basisVerification = "Verifying a Basis"
    case constructingBases = "Constructing Bases"
    case intersectionsExtensions = "Intersections & Extensions"
    case verifyingOrthogonalSets = "Verifying Orthogonal Sets"
    case orthogonalProjection = "Orthogonal Projection"
    case gramSchmidtProcess = "Gram-Schmidt Process"
    case matrixTransformations = "Matrix Transformations"
    case checkingLinearity = "Checking Linearity"
    case transformationsFromBasis = "Transformations from Basis"
    case verifyingIsometries = "Verifying Isometries"
    case rotationsReflections = "Rotations & Reflections"
    case analyzingOrthogonalMatrices = "Analyzing Orthogonal Matrices"
    case compositionOfTransformations = "Composition of Transformations"
    case invertingLinearOperators = "Inverting Linear Operators"
    case kernelAndRange = "Kernel and Range"
    case fundamentalSubspaces = "Fundamental Subspaces"
    case orthogonalComplements = "Orthogonal Complements"
    case symmetricMatrixProducts = "Symmetric Matrix Products"
    case projectionMatrices = "Projection Matrices"
    case computingProjections = "Computing Projections"
    case projectionOrthogonalComplement = "Projection to Complement"
    case pdfExport = "Solution Export"
    case practiceProblems = "Practice Problems"
    case examMode = "Exam Mode"
    case settings = "Settings"
    
    var id: String { rawValue }
    
    var notation: String {
        switch self {
        case .nullSpace: return "N(A)"
        case .columnSpace: return "C(A)"
        case .rowSpace: return "C(Aᵀ)"
        case .leftNullSpace: return "N(Aᵀ)"
        case .inverse: return "A⁻¹"
        case .determinant: return "|A|"
        case .eigenvalues: return "λ"
        case .eigenvectors: return "v"
        case .diagonalization: return "PDP⁻¹"
        case .gramSchmidt: return "QR"
        case .luDecomposition: return "LU"
        case .svd: return "UΣVᵀ"
        case .orthogonality: return "u·v"
        case .vectorArithmetic: return "u+v"
        case .linearCombinations: return "c₁v₁"
        case .parallelVectors: return "u||v"
        case .dotProductApplication: return "p·q"
        case .complexVectorArithmetic: return "||u||"
        case .normalizationScaling: return "û"
        case .anglesBetweenVectors: return "cos θ"
        case .orthogonalSets: return "⊥"
        case .matrixArithmetic: return "A±B"
        case .matrixMultiplication: return "AB"
        case .matrixExponents: return "Aⁿ"
        case .transposeOperations: return "Aᵀ"
        case .specialMatrixTypes: return "△"
        case .verifySolutions: return "✓x"
        case .gaussianElimination: return "GE"
        case .refRref: return "REF"
        case .gaussJordan: return "GJ"
        case .inverse2x2Formula: return "A⁻¹"
        case .inverseGaussJordan: return "[A|I]"
        case .solveWithInverse: return "A⁻¹b"
        case .elementaryMatrices: return "E"
        case .distanceHyperplane: return "dist"
        case .leastSquaresInconsistent: return "LS"
        case .leastSquaresInfinite: return "LS∞"
        case .linearRegression: return "y=mx+b"
        case .quadraticCurveFitting: return "y=ax²+bx+c"
        case .geometric: return "3D"
        case .transformation2D: return "2D"
        case .rankNullity: return "r+n"
        case .permutationsInversions: return "π"
        case .basicDeterminantCalc: return "det"
        case .geometricApplications: return "△"
        case .determinantProperties: return "det"
        case .cofactorExpansionMethod: return "Cᵢⱼ"
        case .adjugateInverse: return "adj"
        case .cramersRule: return "x=det"
        case .orthogonalDiagonalization: return "QᵀAQ"
        case .subspaceVerification: return "⊆"
        case .subspaceOperations: return "∩∪"
        case .spanningSets: return "span"
        case .linearIndependenceBasic: return "c₁v₁"
        case .linearIndependenceAlgorithms: return "det≠0"
        case .findingBases: return "basis"
        case .basisVerification: return "B?"
        case .constructingBases: return "span(S)"
        case .intersectionsExtensions: return "B₁∪B₂"
        case .verifyingOrthogonalSets: return "⊥?"
        case .orthogonalProjection: return "projᵤv"
        case .gramSchmidtProcess: return "GS"
        case .matrixTransformations: return "T(x)"
        case .checkingLinearity: return "L?"
        case .transformationsFromBasis: return "T(B)"
        case .verifyingIsometries: return "||Tx||"
        case .rotationsReflections: return "Rθ"
        case .analyzingOrthogonalMatrices: return "QᵀQ"
        case .compositionOfTransformations: return "S∘T"
        case .invertingLinearOperators: return "T⁻¹"
        case .kernelAndRange: return "ker/im"
        case .fundamentalSubspaces: return "C(A)/N(A)"
        case .orthogonalComplements: return "W⊥"
        case .symmetricMatrixProducts: return "AᵀA"
        case .projectionMatrices: return "P"
        case .computingProjections: return "projᵤw"
        case .projectionOrthogonalComplement: return "I-P"
        case .pdfExport: return "PDF"
        case .practiceProblems: return "✎"
        case .examMode: return "⏱"
        default: return ""
        }
    }
    
    var iconName: String {
        switch self {
        case .matrixSetup: return "grid"
        case .introduction: return "book.fill"
        case .geometric: return "cube.transparent"
        case .inverse: return "1.square"
        case .determinant: return "sum"
        case .eigenvalues: return "function"
        case .eigenvectors: return "arrow.up.left.and.arrow.down.right"
        case .diagonalization: return "arrow.triangle.2.circlepath"
        case .gramSchmidt: return "square.stack.3d.forward.dottedline"
        case .luDecomposition: return "slider.horizontal.3"
        case .svd: return "waveform.path.ecg"
        case .orthogonality: return "angle"
        case .vectorArithmetic: return "plus.forwardslash.minus"
        case .linearCombinations: return "arrow.triangle.branch"
        case .parallelVectors: return "equal"
        case .dotProductApplication: return "dollarsign.circle"
        case .complexVectorArithmetic: return "function"
        case .normalizationScaling: return "arrow.up.right.and.arrow.down.left"
        case .anglesBetweenVectors: return "angle"
        case .orthogonalSets: return "rectangle.3.group"
        case .matrixArithmetic: return "plus.minus"
        case .matrixMultiplication: return "multiply.square"
        case .matrixExponents: return "chevron.up.square"
        case .transposeOperations: return "arrow.up.arrow.down"
        case .specialMatrixTypes: return "triangle.fill"
        case .verifySolutions: return "checkmark.circle"
        case .gaussianElimination: return "arrow.down.to.line.compact"
        case .refRref: return "stairs"
        case .gaussJordan: return "arrow.left.arrow.right"
        case .inverse2x2Formula: return "square.2.layers.3d.top.filled"
        case .inverseGaussJordan: return "rectangle.split.2x1"
        case .solveWithInverse: return "xmark.app"
        case .elementaryMatrices: return "e.square"
        case .distanceHyperplane: return "arrow.up.to.line"
        case .leastSquaresInconsistent: return "exclamationmark.triangle"
        case .leastSquaresInfinite: return "infinity"
        case .linearRegression: return "chart.xyaxis.line"
        case .quadraticCurveFitting: return "chart.line.uptrend.xyaxis"
        case .transformation2D: return "square.grid.2x2"
        case .rankNullity: return "chart.bar.doc.horizontal"
        case .permutationsInversions: return "arrow.left.arrow.right"
        case .basicDeterminantCalc: return "square.grid.2x2"
        case .geometricApplications: return "triangle"
        case .determinantProperties: return "slider.horizontal.3"
        case .cofactorExpansionMethod: return "rectangle.split.3x3"
        case .adjugateInverse: return "arrow.uturn.backward.square"
        case .cramersRule: return "x.squareroot"
        case .orthogonalDiagonalization: return "square.on.square.dashed"
        case .subspaceVerification: return "checkmark.circle"
        case .subspaceOperations: return "arrow.triangle.merge"
        case .spanningSets: return "arrow.up.left.and.arrow.down.right"
        case .linearIndependenceBasic: return "equal.circle"
        case .linearIndependenceAlgorithms: return "function"
        case .findingBases: return "cube"
        case .basisVerification: return "checkmark.seal"
        case .constructingBases: return "hammer"
        case .intersectionsExtensions: return "plus.viewfinder"
        case .verifyingOrthogonalSets: return "checkmark.diamond"
        case .orthogonalProjection: return "arrow.down.to.line"
        case .gramSchmidtProcess: return "wand.and.stars"
        case .matrixTransformations: return "arrow.right.arrow.left"
        case .checkingLinearity: return "questionmark.circle"
        case .transformationsFromBasis: return "arrow.triangle.branch"
        case .verifyingIsometries: return "ruler"
        case .rotationsReflections: return "rotate.right"
        case .analyzingOrthogonalMatrices: return "square.grid.2x2"
        case .compositionOfTransformations: return "arrow.triangle.2.circlepath"
        case .invertingLinearOperators: return "arrow.uturn.backward"
        case .kernelAndRange: return "scope"
        case .fundamentalSubspaces: return "square.stack.3d.down.right"
        case .orthogonalComplements: return "angle"
        case .symmetricMatrixProducts: return "square.on.square"
        case .projectionMatrices: return "square.grid.3x3"
        case .computingProjections: return "arrow.down.right.circle"
        case .projectionOrthogonalComplement: return "arrow.up.and.down.circle"
        case .pdfExport: return "doc.text"
        case .practiceProblems: return "pencil.and.list.clipboard"
        case .examMode: return "timer"
        case .settings: return "gear"
        default: return "" // Custom icon for subspaces
        }
    }
}
